# TCL File Generated by Component Editor 25.1
# Tue Sep 15 11:22:06 CDT 2026
# DO NOT MODIFY


# 
# led_ctrl "led_ctrl" v1.0
# Evan Wu 2026.09.15.11:22:06
# Avalon-MM Slave Agent for controlling LEDs 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module led_ctrl
# 
set_module_property DESCRIPTION "Avalon-MM Slave Agent for controlling LEDs "
set_module_property NAME led_ctrl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Evan Wu"
set_module_property DISPLAY_NAME led_ctrl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_mm_led_ctrl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_mm_led_ctrl.sv SYSTEM_VERILOG PATH ../../rtl/avalon_mm_led_ctrl.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter AddressWidth INTEGER 2 ""
set_parameter_property AddressWidth DEFAULT_VALUE 2
set_parameter_property AddressWidth DISPLAY_NAME AddressWidth
set_parameter_property AddressWidth WIDTH ""
set_parameter_property AddressWidth TYPE INTEGER
set_parameter_property AddressWidth UNITS None
set_parameter_property AddressWidth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AddressWidth DESCRIPTION ""
set_parameter_property AddressWidth HDL_PARAMETER true
add_parameter DataWidth INTEGER 32 ""
set_parameter_property DataWidth DEFAULT_VALUE 32
set_parameter_property DataWidth DISPLAY_NAME DataWidth
set_parameter_property DataWidth WIDTH ""
set_parameter_property DataWidth TYPE INTEGER
set_parameter_property DataWidth UNITS None
set_parameter_property DataWidth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DataWidth DESCRIPTION ""
set_parameter_property DataWidth HDL_PARAMETER true


# 
# display items
# 


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock_sink
set_interface_property csr associatedReset reset_sink
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 1
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_address address Input "((AddressWidth-1)) - (0) + 1"
add_interface_port csr csr_write write Input 1
add_interface_port csr csr_writedata writedata Input "((DataWidth-1)) - (0) + 1"
add_interface_port csr csr_read read Input 1
add_interface_port csr csr_readdata readdata Output "((DataWidth-1)) - (0) + 1"
add_interface_port csr csr_waitrequest waitrequest Output 1
add_interface_port csr csr_readdatavalid readdatavalid Output 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_i reset Input 1


# 
# connection point leds
# 
add_interface leds conduit end
set_interface_property leds associatedClock clock_sink
set_interface_property leds associatedReset ""
set_interface_property leds ENABLED true
set_interface_property leds EXPORT_OF ""
set_interface_property leds PORT_NAME_MAP ""
set_interface_property leds CMSIS_SVD_VARIABLES ""
set_interface_property leds SVD_ADDRESS_GROUP ""

add_interface_port leds led output Output 10

